#ifndef INCLUDED_COMMON_H
#define INCLUDED_COMMON_H

enum error {
    ERROR_SUCCESS = 0,
    ERROR_SOCKET_CREATION_FAILED = 1,
    ERROR_SOCKET_BIND_FAILED = 2,
    ERROR_SOCKET_LISTEN_FAILED = 3
};

#endif
